### ISSUE TITLE
Client is not a constructor

### ISSUE THREAD

**Issue by angelserranoperez** [predicthq/sdk-js#25]
Why appears that kind of error while I try to run this code:
```
var Client = require('predicthq');

var phq = new Client({access_token: "I solved it"});
// YES , I put my access token and I will change in the future but by the way at the momment is not useful because I can not access to the api.

phq.events.search({q: 'Madonna', rank_level: 5, country:'AU', 'start.gte' : '2016-01-01'})
    .then(function(results){
        var events = results.toArray()
        for(var i=0; i < events.length; i++)
            console.info(events[i].rank, events[i].category, events[i].title, events[i].start, events[i].location )
    })
```

/Users/user/Desktop/madrid/predicthqtests/index3.js:3

> var phq = new Client({access_token: "c6gSkMJhi2yqrXBFZ4wBmB8yt1teSd"})
>           ^
> 
> TypeError: Client is not a constructor
>     at Object.<anonymous> (/Users/user/Desktop/madrid/predicthqtests/index3.js:3:11)
>     at Module._compile (module.js:641:30)
>     at Object.Module._extensions..js (module.js:652:10)
>     at Module.load (module.js:560:32)
>     at tryModuleLoad (module.js:503:12)
>     at Function.Module._load (module.js:495:3)
>     at Function.Module.runMain (module.js:682:10)
>     at startup (bootstrap_node.js:191:16)
>     at bootstrap_node.js:613:3

users-MacBook-Air:predicthqtests user$ cat package.json

```
{
  "name": "predicthqtests",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "predicthq": "0.0.18"
  }
}
```

**Comment by angelserranoperez** [comment]
The correct code is this:
```
var fetch = require('node-fetch');
var phq = require('predicthq');

client = new phq.Client({
  access_token: 'c6gSkMJhi2yqrXBFZ4wBmB8yt1teSd',
  fetch: fetch
});

client.events
  .search({
    q: 'Obk',
    rank_level: 3
  })
  .then(function(results) {
    var events = results.toArray();
    for (var i = 0; i < events.length; i++)
      console.info(
        events[i].rank,
        events[i].category,
        events[i].title,
        events[i].start,
        events[i].location
      );
  });
```
